"""
Student information for this assignment:

Replace <Advaiith Pathi> with your name.
On my/our honor, <Advaiith Pathi> and <Vinay Majjiga>, this
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ap64999
UT EID 2: Vrm729
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    '"""
    if len(s) == 0:
        return 0
    length_word = []
    new_lst = []
    for i in s:
        new_lst.append(ord(i))
    for i in range(len(new_lst)):
        for j in range (len(new_lst) - 1, -1, -1):
            new_dict = {}
            if j > i and j!= i:
                for k in range(i, j + 1):
                    if new_lst[k] not in new_dict:
                        new_dict.update({new_lst[k]:1})
                    else:
                        new_dict[new_lst[k]] += 1
                values = 0
                for value in new_dict.values():
                    values += value
                if values == len(new_dict.values()):
                    length_word.append(len(new_lst[i:j+1]))



    return max(length_word)







def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    new_lst = []
    longest = 0
    if len(s) == 0:
        return 0
    for i in s:
        new_lst.append(ord(i))
    for k in range(n):
        new_dict = {}
        for j in range(k, n):
            if new_lst[j] in new_dict:
                new_dict[new_lst[j]] += 1
            else:
                new_dict.update({new_lst[j]:1})
            if sum(new_dict.values()) == len(new_dict.keys()):
                if sum(new_dict.values()) > longest:
                    longest = sum(new_dict.values())


    return longest


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """


    new_lst = []
    new_dict = {}
    start = 0
    length_lst = []
    if len(s) == 0:
        return 0
    for i in s:
        new_lst.append(ord(i))
    for j in range(len(new_lst)):
        if new_lst[j] in new_dict and new_dict[new_lst[j]] >= start:
            length_lst.append(j - start)
            start = new_dict[new_lst[j]] + 1
            new_dict[new_lst[j]] = j
        else:
            new_dict.update({new_lst[j]: j})

        length_lst.append((j+1) - start)




    return max(length_lst)
