"""
Student information for this assignment:

Replace <Advaiith Pathi> with your name.
On my/our honor, <Advaiith Pathi> and <Vinay Majjiga>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ap6499
UT EID 2: vrm729
"""
import sys

def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    lst = [""] * key
    final_string = ''
    row = 0
    pos = True
    for letter in string:
        lst[row] += letter

        if row == 0:
            pos = True
        elif row == key - 1:
            pos = False

        if pos is True:
            row += 1
        else:
            row -= 1

    for i in lst:
        final_string += i
    return final_string

def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """



def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    final = ""
    for letter in string:
        if letter.isalpha():
            final += letter.lower()
    return final

def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    val_1 = ord(p) - ord('a')
    val_2 = ord(s) - ord('a')

    final = (val_1 + val_2) % 26 + ord('a')
    return chr(final)



def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    val_1 = ord(p) - ord('a')
    val_2 = ord(s) - ord('a')

    final = (val_2 - val_1 + 26) % 26 + ord('a')
    return chr(final)


def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    key = 0
    length = len(phrase)
    final = ""
    pos = True
    string = filter_string(string)
    for letter in string:
        final += encode_character(letter, phrase[key])
        if key == 0:
            pos = True
        elif key == length - 1:
            pos = False

        if pos is True:
            key += 1
        else:
            key = 0
    return final

def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm

    """
    key = 0
    length = len(phrase)
    final = ""
    pos = True
    string = filter_string(string)
    for letter in string:
        final += decode_character( phrase[key], letter)
        if key == 0:
            pos = True
        elif key == length - 1:
            pos = False

        if pos is True:
            key += 1
        else:
            key = 0

    return final


def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)
    plain = sys.stdin.read()

    # read the key from stdin (terminal/input)
    key = sys.stdin.read()

    # encrypt and print the encoded text using rail fence cipher
    print(rail_fence_encode(plain, key))

    # read encoded text from stdin (terminal/input)


    # read the key from stdin (terminal/input)

    # decrypt and print the plain text using rail fence cipher

    # read the plain text from stdin (terminal/input)
    encode = sys.stdin.read()

    # read the pass phrase from stdin (terminal/input)
    phrase = sys.stdin.read()

    # encrypt and print the encoded text using Vigenere cipher
    print(vigenere_encode(encode, phrase))

    # read the encoded text from stdin (terminal/input)
    encode_2 = sys.stdin.read()

    # read the pass phrase from stdin (terminal/input)
    phrase_2 = sys.stdin.read()


    # decrypt and print the plain text using Vigenere cipher
    print(vigenere_decode(encode_2, phrase_2))


# Do NOT modify the following code.
if __name__ == "__main__":
    main()
