"""
Student information for this assignment:

Replace <Advaiith Pathi> with your name.
On my/our honor, <Advaiith Pathi> and <Vinay Majjiga>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ap64999
UT EID 2: Vrm729
"""

from abc import ABC, abstractmethod
import random

DAILY_EXPENSE = 60
HAPPINESS_THRESHOLD = 50
MANAGER_BONUS = 1000
TEMP_EMPLOYEE_PERFORMANCE_THRESHOLD = 50
PERM_EMPLOYEE_PERFORMANCE_THRESHOLD = 25
RELATIONSHIP_THRESHOLD = 10
INITIAL_PERFORMANCE = 75
INITIAL_HAPPINESS = 50
PERCENTAGE_MAX = 100
PERCENTAGE_MIN = 0
SALARY_ERROR_MESSAGE = "Salary must be non-negative."


class Employee(ABC):
    """
    Abstract base class representing a generic employee in the system.
    """

    def __init__(self, name, manager, salary, savings):
        self.relationships = {}
        self.savings = savings
        self.is_employed = True
        self.__name = name
        self.__manager = manager
        self.performance = INITIAL_PERFORMANCE
        self.happiness = INITIAL_HAPPINESS
        self.salary = salary

    @property
    def name(self):
        """returns name"""
        return self.__name

    @property
    def manager(self):
        """returns manager"""
        return self.__manager

    @property
    def performance(self):
        """returns performance"""
        return self._performance

    @property
    def happiness(self):
        """returns happiness"""
        return self._happiness

    @property
    def salary(self):
        """returns salary"""
        return self._salary
    @performance.setter
    def performance(self, value):
        if 0 <= value <= 100:
            self._performance = value
        if value > 100:
            self._performance = 100
        elif value < 0:
            self._performance = 0

    @happiness.setter
    def happiness(self, value):
        if 0 <= value <= 100:
            self._happiness = value
        elif  value > 100:
            self._happiness = 100
        elif value < 0:
            self._happiness = 0

    @salary.setter
    def salary(self, value):
        if value >= 0:
            self._salary = value
        else:
            raise ValueError("SALARY_ERROR_MESSAGE.")

    @abstractmethod
    def work(self):
        """abstract method for work function"""
        return

    def interact(self, other):
        """interactions between manager and employee"""
        if other.name not in self.relationships:
            self.relationships.update({other.name:0})
        if self.relationships[other.name] > RELATIONSHIP_THRESHOLD:
            self._happiness += 1
        elif other.happiness >= HAPPINESS_THRESHOLD and self._happiness >= HAPPINESS_THRESHOLD:
            self.relationships[other.name] += 1
        else:
            self.relationships[other.name] -= 1
            self._happiness -= 1

    def daily_expense(self):
        """reduce the employess svaings by DAILY_EXPENSE  and employee's happiness by 1"""
        self.savings -= DAILY_EXPENSE
        self.happiness -= 1


    def __str__(self):
        return (
            f"{self.name}\n"
            f"\tSalary: ${self.salary}\n"
            f"\tSavings: ${self.savings}\n"
            f"\tHappiness: {self.happiness}%\n"
            f"\tPerformance: {self.performance}%"
        )



class Manager(Employee):
    """
    A subclass of Employee representing a manager.
    """

    def work(self):
        value = random.randint(-5, 5)
        if self.performance + value > 100:
            self.performance = 100
        elif self._performance + value < 0:
            self.performance = 0
        else:
            self.performance += value
        if value <= 0:
            self._happiness -= 1
            for i in self.relationships:
                self.relationships[i] -= 1
        else:
            self._happiness += 1




class TemporaryEmployee(Employee):
    """
    A subclass of Employee representing a temporary employee.
    """
    def work(self):
        value = random.randint(-15, 15)
        if self.performance + value > 100:
            self.performance = 100
        elif self._performance + value < 0:
            self.performance = 0
        else:
            self.performance += value
        if value <= 0:
            self._happiness -= 2
        else:
            self._happiness += 1
        if self._happiness > 100:
            self.happiness = 100
        elif self.happiness < 0:
            self.happiness = 0
    def interact(self, other):
        Employee.interact(self, other)
        if self.manager == other:
            if (other.happiness > HAPPINESS_THRESHOLD and
                self.performance >= TEMP_EMPLOYEE_PERFORMANCE_THRESHOLD):
                self.savings += MANAGER_BONUS
            elif other.happiness <= HAPPINESS_THRESHOLD:
                self.salary = self.salary//2
                self.happiness -= 5
                if self.salary == 0:
                    self.is_employed = False

class PermanentEmployee(Employee):
    """
    A subclass of Employee representing a permanent employee.
    """
    def work(self):
        value = random.randint(-10, 10)
        if self.performance + value > 100:
            self.performance = 100
        elif self._performance + value < 0:
            self.performance = 0
        else:
            self.performance += value
        if value >= 0:
            self._happiness +=1
    def interact(self, other):
        Employee.interact(self, other)
        if self.manager == other:
            if (other.happiness > HAPPINESS_THRESHOLD and
                self.performance > PERM_EMPLOYEE_PERFORMANCE_THRESHOLD):
                self.savings += MANAGER_BONUS
            elif other.happiness <= HAPPINESS_THRESHOLD:
                self._happiness -= 1
