"""
Student information for this assignment:

Replace <Adaviith Pathi> with your name.
On my/our honor, <Vinay Majjiga> and <Advaiith pathi>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ap64999
UT EID 2: Vrm729
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"

class LinkedList:
#class to created a Linked List
    def __init__(self):
    #class to created a Linked List
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 3/24. If you choose to use
        # a dummy node, comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
    #method to insert items in order
        new_node = Node(coeff, exp)
        if self.head is None and coeff != 0:
            self.head = new_node
            self.head.next = None
        else:
            if coeff != 0:
                current = self.head
                if exp > current.exp:
                    new_node.next = current.next
                    current.next = new_node
                elif exp == current.exp:    #fix later !!!!!!
                    current.coeff += coeff
                else:
                    while current.next is not None:
                        if current.next.exp == exp:
                            current.next.coeff += coeff
                        elif exp > current.next.exp:
                            new_node.next = current.next
                            current.next = new_node
                        current = current.next
                    new_node.next = current.next
                    current.next = new_node

    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
        result = LinkedList()
        poly2 = p.head
        current = self.head
        if current is None and poly2 is None:
            return result
        elif current.exp > poly2.exp:
            result.insert_term(current.coeff, current.exp)
            result.insert_term(poly2.coeff, poly2.exp)
        elif current.exp < poly2.exp:
            result.insert_term(poly2.coeff, poly2.exp)
            result.insert_term(current.coeff, current.exp)
        elif current.exp == poly2.exp:
            coefficient = current.coeff + poly2.coeff
            result.insert_term(coefficient, current.exp)
        return result
    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        result = LinkedList()
        current = self.head
        poly2 = p.head
        if current is None or poly2 is None:
            return result
        while current is not None:
            poly2 = p.head
            while poly2 is not None:
                coefficent = poly2.coeff * current.coeff
                exponent = poly2.exp + current.exp
                result.insert_term(coefficent, exponent)
                poly2 = poly2.next
            current = current.next
        return result

    # Return a string representation of the polynomial.
    def __str__(self):
        output = ""
        current = self.head
        if current is None:
            return output
        output += f"({current.coeff}, {current.exp})"
        current = current.next
        while current is not None:
            output += f" + ({current.coeff}, {current.exp})"
            current = current.next
        return output


# read data from stdin (terminal/file) using input() and create polynomial p
def main():
    # read data from stdin (terminal/file) using input() and create polynomial p
     # read data from stdin (terminal/file) using input() and create polynomial q
    p = ""
    q = ""
    p_list = []
    q_list = []
    len_p = int(input())
    for _ in range(len_p):
        value = input().split()
        coeff = int(value[0])
        exp = int(value[1])
        p_list.append((coeff, exp))
    input()
    len_q = int(input())
    for _ in range(len_q):
        q_val = input().split()
        q_coeff = int(q_val[0])
        q_exp = int(q_val[1])
        q_list.append((q_coeff, q_exp))
    for i in range(len(p_list)-1):
        p += f"{p_list[i]} + "
    p += f"{p_list[len(p_list)-1]}"

    for j in range(len(q_list)-1):
        q += f"{q_list[j]} + "
    q += f"{q_list[len(q_list)-1]}"
    poly = LinkedList()
    for values in p_list:
        poly.insert_term(values[0], values[1])
    added = LinkedList()
    for values in p_list:
        added.insert_term(values[0], values[1])
    multiplication = LinkedList()
    for values in p_list:
        multiplication.insert_term(values[0], values[1])
    for adding in q_list:
        added.add(adding)
    for multiply in q_list:
        multiplication.mult(multiply)
    print(added)
    print(multiplication)
if __name__ == "__main__":
    main()
