"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <FULL NAME> and <FULL NAME>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:
UT EID 2:
"""


def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums)  and target == 0:
        return True

    if start >= len(nums)  and target != 0:
        return False



    return group_sum(start + 1, nums, target - nums[start]) or group_sum(start + 1 , nums, target )




def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums) and target == 0:
        return True

    if start >= len(nums) and target != 0:
        return False

    if nums[start] == 6:
        return group_sum_6(start + 1, nums, target - 6 )



    return (group_sum_6(start + 1, nums, target - nums[start]) or
            group_sum_6(start + 1, nums, target))


def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums)  and target == 0:
        return True

    if start >= len(nums)  and target != 0:
        return False



    return (group_no_adj(start + 2, nums, target - nums[start]) or
            group_no_adj(start + 2 , nums, target ))





def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """

    if start >= len(nums) and target == 0:
        return True

    if start >= len(nums) and target != 0:
        return False

    if nums[start] % 5 == 0:
        return group_sum_5(start + 1, nums, target - nums[start])

    if nums[start]  == 1 and nums[start -1 ] % 5 == 0:
        return group_sum_5(start + 1, nums, target)

    return (group_sum_5(start + 1, nums, target - nums[start]) or
            group_sum_5(start + 1, nums, target))





def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise

    """

    if start >= len(nums) and target == 0:
        return True

    if start >= len(nums) and target != 0:
        return False

    if start > 0 and nums[start] == nums[start - 1] :
        return group_sum_clump(start + 1, nums, target - nums[start])

    elif start < len(nums) -1 and nums[start] == nums[start + 1]:
        return group_sum_clump(start + 1, nums, target - nums[start])


    return (group_sum_clump(start + 1, nums, target - nums[start]) or
            group_sum_clump(start + 1, nums, target))

def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    if sum(nums) % 2 != 0:
        return False
    else:
        target  = sum(nums)//2
        start = 0
        return split_array_helper(nums, start, target)



def split_array_helper(nums,  start, target):
    """ helper function """
    if start >= len(nums) and target == 0:
        return True
    if start >= len(nums) and target != 0:
        return False


    return (split_array_helper(nums, start + 1, target - nums[start]) or
            split_array_helper(nums, start + 1, target))


def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    if sum(nums) %2 == 0 or sum(nums) < 11:
        return False
    target1  = 0
    target2 = 0
    start = 0
    return split_odd_10_helper(nums, start, target1, target2)


def split_odd_10_helper(nums, start, target1, target2):
    """helper function"""
    if start >= len(nums) and target1 %10 == 0:
        return True

    if start >= len(nums) and target2 % 2 != 0:
        return True

    if start >= len(nums):
        return False

    return (split_odd_10_helper(nums, start + 1, target1 + nums[start], target2 + nums[start]) or
            split_odd_10_helper(nums, start + 1, target1, target2))





def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    if sum(nums) %2 != 0:
        return False
    target1  = sum(nums)//2
    target2 = sum(nums)//2
    start = 0
    return split_53_helper(nums, start, target1, target2)
#helper function for split53()
def split_53_helper(nums, start, target1, target2):
    """helper function"""
    if start >= len(nums) and target1 == 0 and target2 == 0:
        return True

    if start >= len(nums):
        return False

    if nums[start] %3 == 0:
        return split_53_helper(nums,start + 1, target1 - nums[start], target2)

    if nums[start] % 5 ==0:
        return split_53_helper(nums, start + 1, target1, target2 -nums[start])

    return  (split_53_helper(nums,start + 1, target1 - nums[start], target2) or
             split_53_helper(nums, start + 1, target1, target2 - nums[start]))
